# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0f0807dcb68e30c892af2acb37ab340aae04a03e5843c6aefb1f0153fec2ae1220d25d949bf04f4252e6300e19108800cb941c5d355d6eb15bb5fc092cc8474d

test:
  secret_key_base: d660bcaf5932fdbf07593be2738bdac09c3af67406536826153a3d16ab1288288cd6c9cae1a66c516fba6e4934e56caa590eba7b1a44915ec0b9ba87aab6d09c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
